name: master
on:
  push:
    branches:
      - master
permissions: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        with:
          # https://www.npmjs.com/package/semver#caret-ranges-123-025-004
          go-version: '^1.21'
          check-latest: true
      - run: go version
      - run: go vet ./github ./google ./zalando
      - run: go test ./...
      - run: go test -race ./...
